version: "3"
services:
  code-server:
    image: imba97/code-server:latest
    container_name: code-server
    hostname: code-server
    environment:
      # code-server 登录密码
      # 配置在 Dockerfile 上传镜像后会显示出来
      # 所以还是放在本地自己改成其他的
      - PASSWORD=123
      # NPS 配置
      - NPS_SERVER=
      - NPS_KEY=
    volumes:
      - code-server:/home/coder
    ports:
      - 1022:22/tcp
      - 6020:8080/tcp
    restart: unless-stopped
    networks:
      - general

volumes:
  code-server:

networks:
  general:
