ZSH="$HOME/.oh-my-zsh"
ZSH_CUSTOM="$HOME/.oh-my-zsh/custom"
ZSH_THEME="spaceship"
plugins=(git)
ZSH_CACHE_DIR="$HOME/.cache/oh-my-zsh"

if [[ ! -d "$ZSH_CACHE_DIR" ]]; then
  mkdir -p "$ZSH_CACHE_DIR"
fi

source "$ZSH/oh-my-zsh.sh"

export DEFAULT_WORKSPACE="${DEFAULT_WORKSPACE:-$HOME/workspace}"
if [[ ! -d "$DEFAULT_WORKSPACE" ]]; then
  mkdir -p "$DEFAULT_WORKSPACE"
fi

if [[ -f "$HOME/.oh-my-zsh/custom/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh" ]]; then
  source "$HOME/.oh-my-zsh/custom/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh"
fi

if [[ -f "$HOME/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" ]]; then
  source "$HOME/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
fi

alias ll="ls -l --color=auto"
alias ls="ls --color=auto"
alias cp="cp -i"
alias mv="mv -i"
export EDITOR="${EDITOR:-vi}"
export VISUAL="$EDITOR"

[ -f "$HOME/.zshrc.user" ] && source "$HOME/.zshrc.user"
